#For creating Kubernetes Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ack
  template:
    metadata:
      labels:
        app: ack
    spec:
      containers:
      - name: ack
        image: zsoltadam/ack-service
        ports:
        - containerPort: 8081
---
#For creating a Kubernetes Service
apiVersion: v1
kind: Service
metadata:
  name: ack-service
spec:
  type: ClusterIP
  selector:
    app: ack
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081