apiVersion: apps/v1
kind: Deployment
metadata:
    name: db
    labels:
        app: db
        group: db
spec:
    replicas: 1
    selector:
        matchLabels:
            app: db
    template:
        metadata:
            labels:
                app: db
                type: db
        spec:
            volumes:                        # indicates which PVC are available for this Deployment
                - name: db-storage
                  persistentVolumeClaim:
                      claimName: db-persistent-volume-claim
            containers:
                - name: db
                  image: postgres:12.0-alpine
                  ports:
                      - containerPort: 5432
                  envFrom:
                      - configMapRef:
                            name: db-config
                  volumeMounts:              # indicates which Volume (from spec.template.spec.volumes) should be used
                      - name: db-storage   # name of the Volume
                        mountPath: /var/lib/postgresql/data   # path inside the container
                  resources:
                      limits:
                          memory: "256Mi"
                          cpu: "500m"