#For creating Kubernetes Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: report
  labels:
    app: report
    group: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: report
  template:
    metadata:
      labels:
        app: report
        group: db
    spec:
      containers:
      - name: report
        image: zsoltadam/report-service
        ports:
        - containerPort: 8080
        env:
          - name: SPRING_DATASOURCE_URL
            value: jdbc:postgresql://$(DB_SERVICE_HOST):5432/qalevDB
          - name: SPRING_DATASOURCE_USERNAME
            value: admin
          - name: SPRING_DATASOURCE_PASSWORD
            value: "1234"
---
#For creating a Kubernetes Service
apiVersion: v1
kind: Service
metadata:
  name: report-service
  labels:
    group: db
spec:
  type: ClusterIP
  selector:
    app: report
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080